[build]
  functions = "functions"   


[schedule.functions.fetch-and-post]
  cron = "30 1 * * *"  


[[scheduled]]
  path = "/.netlify/functions/cronjob"
  cron = "0 20 * * *"

[functions]
  external_node_modules = ["mongoose", "snoowrap", "axios"]  
   directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200